### ISSUE TITLE
Display bug, There is a blocky diagonal line in the editor

### ISSUE THREAD

**Issue by Taohanxu** [NickeManarin/ScreenToGif#906] opened 2021-05-30 12:56 UTC
Hi,
There is a pixel block line in the editor, no matter I change the theme, language or delete the setting.xaml file, it still appears.

![image](https://user-images.githubusercontent.com/70997554/120104675-37c06200-c188-11eb-8eae-bb1eb7c27dc5.png)
![image](https://user-images.githubusercontent.com/70997554/120104703-663e3d00-c188-11eb-832f-4f2c895e9de7.png)

(this is my first time submitting an issue,please forgive me if there is any irregularity. )

**Comment by pawlos** [comment] 2021-05-30 18:14
It looks like this is connected to AMD driver https://github.com/NickeManarin/ScreenToGif/issues/737#issuecomment-752398292

**Comment by NickeManarin** [comment] 2021-05-30 18:15
Duplicate of #790

**Comment by NickeManarin** [comment] 2021-05-30 18:15
Disable hardware rendering on Options > General.

**Closed by NickeManarin** 2021-05-30 18:15 UTC

**Comment by Taohanxu** [comment] 2021-05-31 03:18
Thanks
