### ISSUE TITLE
Use .NET 6

### ISSUE THREAD

**Issue by majkinetor** [NickeManarin/ScreenToGif#579] opened 2020-01-13 10:43 UTC
Cross platformness is something that was asked number of times here.

Now, .Net Framework 4.6 is dead and .NET Core is where all the things will happen. Migrating to it would be great for both maintainabilaty and futre prospects on cross platformness. For example, v3 added WPF (for Windows only currently). 

This will make it much easier to achieve Linux/Mac port in the future - maybe WPF will become x-platform itself, or it can be switched to something else like Avalon or whatever... There is also option to use [wine](https://ccifra.github.io/PortingWPFAppsToLinux/Overview.html) with WPF on linux. 

So, switching to net core provides a lot of more options, and it must be done sooner or later anyway.

**Comment by NickeManarin** [comment] 2020-01-19 18:49
I'm thinking in switching to .NET Core. I just haven't really studied about it.
Mainly what would be the impact on the current codebase, what user would need to do in order to run the app, etc.

**Comment by majkinetor** [comment] 2020-01-19 20:15
Well that is really the only way to go in the not so distant future. 

>  what user would need to do in order to run the app, 

That is finally legit in core, since it can have systemic framework, local framework (in app dir), you can compile it into exe or even cherry pick assemblies you want etc..

**Comment by vatterspun** [comment] 2020-01-20 18:17
This is all moot if you don't have a choice, but the notion/promise that a cross-platform .NET is just around the corner has been around for at least a decade.  I am very glad to be wrong about this but I wouldn't drop your current effort for the ability to run on Mac/Linux/etc.

**Comment by majkinetor** [comment] 2020-01-20 18:20
I am very glad you are wrong too.

**Comment by vatterspun** [comment] 2020-01-20 18:36
> I am very glad you are wrong too.

Uh, great

**Comment by NickeManarin** [comment] 2020-01-20 19:01
Lets keep it civil.

I understand that I'll have to switch to .NET "Core" in the future. What I don't know is if they are going to enable some sort of cross platform UI.

If not (and if I want to distribute the app to macOS and Linux), I'll have to resort to Xamarin (Native UI + NetStandard lib).

**Comment by marzhall** [comment] 2020-01-20 19:13
Just a small note: as someone who's had to look at .Net Core for work in the last year, the issue is indeed still that there's no GUI library packaged with Core, and we weren't able to find a good OSS one to use. So, I can lend some support to that likely being the biggest hurdle in this effort.

As an additional aside, as someone who's fulltime Linux, I recognize we're a pretty small chunk of users. That said, this is the only application I miss from Windows. <3

**Comment by majkinetor** [comment] 2020-01-20 19:48
> Lets keep it civil

Sure. Not sure what was not civil tho.

> What I don't know is if they are going to enable some sort of cross platform UI.

Ofc they will. There is one now already, [Avalonia](https://avaloniaui.net/) which was even used initially in pwsh'g `Out-GridView`.  But that is irrelevant. Just switching to core has huge performance, methodology, testing and other beneffits, and provides bunch of new options on any front. It will be much easier for random guy to try to make x-platform solution on core, once it works on core in non-platform-GUI way (i.e. wpf on core 3)

**Comment by NickeManarin** [comment] 2020-01-20 21:05
Here is a guide for WPF .NetFramework to .NetCore:

https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework

**Comment by kirsan31** [comment] 2020-02-14 16:50
@NickeManarin [this](https://github.com/dotnet/try-convert) can help a bit with project converting.
I agree with @majkinetor that 1 step must be switch to core. Simple because it's .net future.
And then, may be (if needed), switch from WPF to [Avalonia](https://github.com/AvaloniaUI/Avalonia)...

**Comment by Lakritzator** [comment] 2020-03-03 09:43
I'm the writer of Greenshot, and just wanted to give you my opinion:
* WPF or WinForms just works fine with dotnet core 3.1, minimum changes!
* There is currently no x-plat solution for a UI, but this would not be the only challenge you have (capturing the screen, webcam etc)
* The biggest issue for Greenshot is the packaging, you cannot assume there is a dotnet core 3.1 runtime installed so you will need to bring this yourself -> blowing up the download size

If you ever have any dotnet core 3.1 specific questions for desktop applications just let me know.

**Comment by mabakay** [comment] 2020-09-21 13:16
Maybe wait for .NET 5?

**Comment by NickeManarin** [comment] 2020-09-21 13:19
@mabakay Yes, I'm waiting for .NET 5

**Comment by srbala** [comment] 2020-10-09 12:27
.NET 5, RC1 is here, means API is stable and only bug fixes before final release...!

**Comment by DarkOoze** [comment] 2020-11-06 10:19
I had a go at this and got it to build with minor changes, but there where some issues at runtime.
BeginInvoke on delegate is not supported in the core runtime and will throw PlatformNotSupportedException.

The size of the published exe got pretty big (as @Lakritzator expected).
Using self-contained executable targeting 3.1 resulted in a ~160 MB exe (~150 MB after trimming). I guess a big part of this is the use of both WCF and WinForm references.

**Comment by NickeManarin** [comment] 2020-11-10 16:27
@DarkOoze Have you tried to use .NET 5? What about a non self-contained build?

**Comment by DarkOoze** [comment] 2020-11-13 14:47
NET5 trimmed it down to ~90MB but there is missing runtime as it crash on startup. Have not analyzed what is missing.

BeginInvoke is still an issue. It is deprecated and will not come to Core.

Framework-dependent is ~6MB, but not sure how to handle the dependency. [ClickOnce ](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-2/#clickonce)might be an option?

The source of the build:
https://github.com/DarkOoze/ScreenToGif/tree/dotnet-core

**Comment by NickeManarin** [comment] 2020-11-13 16:44
> BeginInvoke is still an issue. It is deprecated and will not come to Core.

I believe most of the calls can be easily replaced by `await`.

> Framework-dependent is ~6MB, but not sure how to handle the dependency. 

Perhaps the same way as today with .NET Framework 4.8? 
I hope that .NET 5 starts to get distributed with Windows too.
But in case no dependency is found, a message should appear.

**Comment by CatTheHacker** [comment] 2020-11-25 02:48
> I hope that .NET 5 starts to get distributed with Windows too.

It won't be included in Windows. [¹]

> I agree with majkinetor that 1 step must be switch to core. Simple because it's .net future.

It's only a "must be" if you want new features. .NET Framework will stay in Windows and will receive security and bug fixes but it won't be developed anymore.

[¹]: https://github.com/dotnet/core/issues/4600#issuecomment-725613982

**Comment by John0King** [comment] 2021-04-08 09:04
cross platform UI   try  http://avaloniaui.net/

**Comment by majkinetor** [comment] 2021-04-08 09:23
Its probably better to wait for official one: https://devblogs.microsoft.com/xamarin/the-new-net-multi-platform-app-ui-maui/

**Comment by gfoidl** [comment] 2021-04-21 19:14
When moving to .NET 5 (or 6) this also opens the door for a lot of performance improvements.
* a lot of (intermediate) allocations could be avoided, so less memory usage and work for the GC
* more performant routines provided by the framework can be used for "free" (they don't need to be re-implemented here for .NET 4.8)

I'm aware that there my be bigger concerns, but as a impatient person it would be nice to half down the time needed to save a recording 😃 

I only had a [quick look](https://github.com/gfoidl/ScreenToGif/tree/perf) into the code-base, and saw that the potential is huge.
With .NET 4.8 it doesn't make a lot of sense to continue perf-improvements, but I'd like to help out when switched to .NET 5+.
(If there's any interest, then just ping me.)

**Comment by NickeManarin** [comment] 2021-04-21 19:31
@gfoidl 
I'm currently working on improving the capture methods, and I should start working on changes for +NET5 shortly afterwards (weekend).

If you would like to help, that would be nice. :)

**Comment by John0King** [comment] 2021-04-27 07:04
.net MAUI not support Win7 ,  sadly :(

**Comment by kirsan31** [comment] 2021-04-27 07:08
> .net MAUI not support Win7 , sadly :(

And linux. Imho avalonia is the choise in terms of cross platform UI and also it's  has WPF roots.

**Comment by NickeManarin** [comment] 2021-05-02 01:39
I'm working on this task now.

For those who tried converting the project to .NET 5:

Did you use the upgrade assistant to upgrade to .NET 5?
What did you do with the App.config?
Is there a replacement for IpcChannel?

**Comment by NickeManarin** [comment] 2021-05-02 01:39
I'm working on this task now.

For those who tried converting the project to .NET 5:

Did you use the upgrade assistant to upgrade to .NET 5?
What did you do with the App.config?
Is there a replacement for IpcChannel?

**Comment by NickeManarin** [comment] 2021-05-02 01:44
> Is there a replacement for IpcChannel?
No... but yes?
https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable#remoting

**Comment by NickeManarin** [comment] 2021-05-02 02:34
I can't create mutexes with a specific security detail:

```cs
var sec = new MutexSecurity();
sec.AddAccessRule(new MutexAccessRule(Environment.UserDomainName + "\\" + Environment.UserName, MutexRights.FullControl, AccessControlType.Allow));

var mutex = new Mutex(false, @"Global\ScreenToGif" + key.Remove("\\"), out bool created, sec);
```

**Comment by mabakay** [comment] 2021-05-02 08:21
> When moving to .NET 5 (or 6) this also opens the door for a lot of performance improvements.

If someone says that he needs new framework for do any real performance optimization I am little sceptic. Performance optimizations are made by using the profiler not by changing code with synthetic sugar from newer compiler ;-)

**Comment by kirsan31** [comment] 2021-05-02 08:41
@NickeManarin 

> Did you use the upgrade assistant to upgrade to .NET 5?

From our experience it's ok for simple project and bad for complex (for example with many native x86/x64 libraries). An any way your need manual tuning after,

> What did you do with the App.config?

We ended up giving it up.

> Is there a replacement for IpcChannel?

I think you already know the answer :)



> I can't create mutexes with a specific security detail:
> 
> ```cs
> var sec = new MutexSecurity();
> sec.AddAccessRule(new MutexAccessRule(Environment.UserDomainName + "\\" + Environment.UserName, MutexRights.FullControl, AccessControlType.Allow));
> 
> var mutex = new Mutex(false, @"Global\ScreenToGif" + key.Remove("\\"), out bool created, sec);
> ```

You need to use [ThreadingAclExtensions ](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadingaclextensions?view=net-5.0) and do like this:
```cs
var mutex = new Mutex(false, @"Global\ScreenToGif" + key.Remove("\\"), out bool created);
var sec = new MutexSecurity();
sec.AddAccessRule(new MutexAccessRule(Environment.UserDomainName + "\\" + Environment.UserName, MutexRights.FullControl, AccessControlType.Allow));
mutex.SetAccessControl(sec);
```

**Comment by gfoidl** [comment] 2021-05-02 10:11
> If someone says that he needs new framework for do any real performance optimization I am little sceptic. Performance optimizations are made by using the profiler not by changing code with synthetic sugar from newer compiler ;-)

What if the framework provides new capabilities to use?
What if the framework itself got faster and we use that work as grounding for this work?
(And of course I had a look through profilers to see what's going on).

**Comment by DarkOoze** [comment] 2021-05-02 13:12
> Is there a replacement for IpcChannel?

I replaced it with JSON over a named pipe.
https://github.com/NickeManarin/ScreenToGif/commit/c267f1a5bf75fd274da743eb8872feff49166c02

**Comment by NickeManarin** [comment] 2021-05-02 20:08
Thanks @kirsan31 and @DarkOoze for the code samples.

**Comment by NickeManarin** [comment] 2021-05-02 20:09
Hmm... I simply removed these three assemblies, no issues so far.

![image](https://user-images.githubusercontent.com/14798947/116825960-02fcc300-ab68-11eb-9ffe-1c83838966a0.png)

**Comment by NickeManarin** [comment] 2021-05-02 20:12
I'm simply replacing all `BeginInvoke()` calls with `await Task.Run()` to make it work, but the idea is to revise everything.

Specially the Editor, Webcam and Board recorders, which are going to be reworked.

**Comment by NickeManarin** [comment] 2021-05-02 20:15
Publishing as a single executable with no loose dll's in the folder is my target too.

Using this command over my base takes a long time and generates a 104MB executable which does not work...

```
dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true /p:IncludeNativeLibrariesForSelfExtract=true
```

![image](https://user-images.githubusercontent.com/14798947/116826318-ccc04300-ab69-11eb-9692-a8bfd3d7aa5e.png)

**Comment by kirsan31** [comment] 2021-05-02 20:22
@NickeManarin I don't know about wpf, but trimming in WinForms have many many problems (if work at all).

**Comment by NickeManarin** [comment] 2021-05-02 20:47
Yeah, that's it. 

Size goes to 176MB but it works.

**Comment by kirsan31** [comment] 2021-05-02 20:51
I hope there will be an option to download framework dependent release 🤣

**Comment by NickeManarin** [comment] 2021-05-30 18:24
For later: https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5

**Comment by NickeManarin** [comment] 2021-07-26 12:37
I would like some help with testing the branch feature/579 or the binaries bellow.

[x64.zip](https://github.com/NickeManarin/ScreenToGif/files/6878147/x64.zip)

**Comment by MaledongGit** [comment] 2021-07-31 12:26
BTW: According to NET's development roadmap, it seems GA for odd number version, while even for LTS since NET 5.0, So maybe You can wait for NET 6's coming but prepare based on .NET 5.0. I'd like to say "Waiting for your version based on NET 6 (or future) even number LTS version.

![image](https://user-images.githubusercontent.com/52018749/127739801-b3ea3965-fdc7-438e-9d02-bf0f9a24c616.png)

For more, you can refer to : https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by MaledongGit** [comment] 2021-07-31 12:28
@NickeManarin: Maybe even number version is better, so NET 5 / odd number version is only for studying, while LTS version for development and production ;)

**Comment by kirsan31** [comment] 2021-07-31 15:39
> I would like some help with testing the branch feature/579 or the binaries bellow.
> 
> [x64.zip](https://github.com/NickeManarin/ScreenToGif/files/6878147/x64.zip)

At first look both .Net5 and .Net6 versions works fine. Win10 20H2.

**Comment by NickeManarin** [comment] 2021-11-30 02:42
I just merged the branch with the migration for .NET 6.

**Closed by NickeManarin** 2021-11-30 02:42 UTC
Labels: 🔷Enhancement, ⬜ In Progress

**Comment by bairog** [comment] 2021-11-30 05:58
> I just merged the branch with the migration for .NET 6.

Is it going to be merged to **master**? For now all commits are in **feature/579-migrate-to-net6** branch..

**Comment by NickeManarin** [comment] 2021-11-30 15:17
@bairog After the release.
During development, the dev branch is used instead.

**Comment by mabakay** [comment] 2021-12-30 18:46
Hey and what with performance? Is the application already faster because of running under .NET 6 runtime?

**Comment by kirsan31** [comment] 2021-12-30 18:49
> Hey and what with performance? Is the application already faster because of running under .NET 6 runtime?

https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core/
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core-2-1/
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core-3-0/
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/
