### ISSUE TITLE
can support macOS  ?

### ISSUE THREAD

**Issue by luckywzy** [NickeManarin/ScreenToGif#772] opened 2020-12-25 10:42 UTC
I not found how to build in macOS system, Does it support？

**Comment by YalandHong** [comment] 2020-12-28 11:52
Duplicate of #481, #29 and many others.
It seems that this application relies on some features available only for Windows.

For more information about cross-platform, please track #579.

Hope this is helpful to you.

**Comment by NickeManarin** [comment] 2020-12-28 19:54
I hope that with .NET MAUI, I'll be able to provide a cross-platform solution.

**Closed** 2020-12-28 19:54 UTC
Labels: duplicated
