### ISSUE TITLE
Add standard shapes to Overlay options (line, rectangle, circle)

### ISSUE THREAD

**Issue by ghost** [NickeManarin/ScreenToGif#363] opened 2018-07-30 16:03 UTC
Free-drawing a rectangle or even a straight line is difficult.

![image](https://user-images.githubusercontent.com/41919579/43408858-ad5d000e-9422-11e8-8170-e04ac80dc617.png)

**Comment by user7285** [comment] 2018-07-30 16:06
Duplicate of #284.

**Comment by NickeManarin** [comment] 2018-08-24 20:54
Closing this one because it`s a duplicate.
I started working with this feature btw. I`m hoping that it will be ready for the next release.

**Closed by NickeManarin** 2018-08-24 20:54 UTC
