### ISSUE TITLE
Incorrect save path

### ISSUE THREAD

**Issue by MariaStoica** [NickeManarin/ScreenToGif#46] opened 2016-12-05 22:21 UTC
When I hit "save as" and choose a path, it fills the path box with a ref path such as ".. \ .. \ .. \ .. \Downloads". After I give the file a name it processes it but at the end it says 0B. I got around this by filling the path box myself with the full path eg: "D:\MyStuff" and then it worked. 
Thanks for this project :) it's really cool.

**Comment by NickeManarin** [comment] 2016-12-06 01:14
It detects the path (before opening the folder picker) as relative and transforms the chosen path to a relative form too.

Now, for some reason the save is not working. :?

**Comment by NickeManarin** [comment] 2017-01-22 03:04
I could not reproduce this issue with the latest version (2.4), could you confirm that it's working?

Expected behavior:
1. If the latest folder path is relative before opening the file picker, then the new path is also converted to relative.
2. If it's not relative, the selected path will stay as non relative.

Both relatives and non-relatives path should work and produce a gif/video.

**Comment by MariaStoica** [comment] 2017-01-22 14:34
I also couldn't reproduce it in 2.4. Seems fixed. Thanks!

**Comment by NickeManarin** [comment] 2017-01-22 14:54
Awesome! Closing this issue.

**Closed by NickeManarin** 2017-01-22 14:54 UTC
Labels: bug
