### ISSUE TITLE
Copy link copies a PNG file rather than the gif

### ISSUE THREAD

**Issue by nickdiacre** [NickeManarin/ScreenToGif#470] opened 2019-03-25 14:33 UTC
On hitting "save as... copy link" the data on the clipboard is just the last PNG frame and not the actual animated GIF...

**Comment by ajayyy** [comment] 2019-05-27 01:19
Same with copy as image, but I kind of understand that.

**Comment by erickmp07** [comment] 2020-04-02 21:47
I want to fix this bug.
Can you describe the steps to reproduce it?

**Comment by ajayyy** [comment] 2020-04-02 21:49
It might be intended as the clipboard has a maximum size.

This occurs when you hit export and then click the copy image button on the export dialog

**Comment by erickmp07** [comment] 2020-04-02 22:49
I'm sorry, but I can't reproduce this bug.
The Copy Image Button on the Export Dialog doesn't exist at version 2.22.1 or I couldn't find it.

**Comment by nickdiacre** [comment] 2020-04-02 23:08
Thanks for looking into this...

Just tested...

* Create recording
* Go to "Save As"
* Select "Copy to Clipboard" as output
* Got to app - in my case Mailbird, Discord or Slack
* Paste

The result is a PNG plus text linking to the file.

Nick


On 02/04/2020 23:49:19, Erick Macedo Pinto <notifications@github.com> wrote:
I'm sorry, but I can't reproduce this bug.
The Copy Image Button on the Export Dialog doesn't exist at version 2.22.1 or I couldn't find it.

**Comment by NickeManarin** [comment] 2020-04-02 23:10
There's two places where you can set to copy the generated gif:

![image](https://user-images.githubusercontent.com/14798947/78307382-1e883b00-751c-11ea-9420-ba7a3b52b568.png)

![image](https://user-images.githubusercontent.com/14798947/78307527-7cb51e00-751c-11ea-9cd9-0f0678068275.png)

The first that says "File" is the same as the "Copy" button on the second one.

The problem here is that there's no Windows API to properly add a GIF to the clipboard, with all frames.

https://stackoverflow.com/a/19823589/1735672

(I'm going to try something different)

**Comment by nickdiacre** [comment] 2020-04-02 23:11
yes I was using file, should have added that...

**Comment by nickdiacre** [comment] 2020-04-02 23:12
Both options, using "file" and right clicking the completed result yield the same outcome

**Comment by erickmp07** [comment] 2020-04-02 23:20
So the issue doesn't have a solution at this moment, right?

**Comment by NickeManarin** [comment] 2020-04-02 23:42
Kind of. I'm going to replace the code of the File/Copy options to follow the same behavior as doing Ctrl + C with the file selected on Windows Explorer.

Also, I'm going to remove the "Copy as Image".

**Comment by NickeManarin** [comment] 2020-04-03 00:06
Closing this as not possible to fix, but with a code tweak.

**Closed by NickeManarin** 2020-04-03 00:06 UTC
