### ISSUE TITLE
Recording position and size are not scaled on high-density display

### ISSUE THREAD

**Issue by ironfroggy** [NickeManarin/ScreenToGif#332] opened 2018-06-02 02:33 UTC
On a high-density display like a Surface device and presumably others the position and size of the recording region are only half what they should be. Attaching the window i had setup and the recording it made.
![s2g_1](https://user-images.githubusercontent.com/34982/40869577-bcb7d64c-65eb-11e8-92ee-ebcd525ecdb4.png)
![s2g_2](https://user-images.githubusercontent.com/34982/40869578-bcd63ede-65eb-11e8-99da-e9ae74c3e314.png)

**Comment by NickeManarin** [comment] 2018-06-02 02:34
Are you using the latest version, v2.13.3?

**Comment by NickeManarin** [comment] 2018-06-10 19:11
Not sure what I'm doing differently, but I could not reproduce this behavior.
I tried with 125% and 150%, using the old or the new recorder, moving or not the recording area.
Can you tell me which scale (or DPI) your Surface screen is using?

**Comment by ironfroggy** [comment] 2018-06-15 02:43
The scale is at 200%, but I just tested on 150% and get the same kind of results. It seems like Screen2GIF is recording based on unscaled coordinates?

**Comment by NickeManarin** [comment] 2018-06-24 21:18
Yes, it's taking a non-scaled position. Do you have multiple screens?

**Comment by ironfroggy** [comment] 2018-06-24 23:16
This happens the same when I have either 1 or 2 screens.

If I were to setup a local dev setup for this, maybe I could help to diagnose it or even fix it...

**Comment by NickeManarin** [comment] 2018-06-25 00:58
I tried more situations while the _recorder was loaded_ and also _before it was open_:
Adding a secondary monitor. 
Removing the secondary monitor.
Changing the position of the screen.
Changing the DPI of the secondary screen (while attached to the left/right of the main screen).
Changing the DPI of the main screen.

It would be really helpful if you would debug this. :)
Inside the **[Recorder.xaml.cs](https://github.com/NickeManarin/ScreenToGif/blob/master/ScreenToGif/Windows/Recorder.xaml.cs)** file, there's a method called **[UpdateScreenDpi()](https://github.com/NickeManarin/ScreenToGif/blob/848e610a3a988ee659933fd78a1cd246de1ade50/ScreenToGif/Windows/Recorder.xaml.cs#L116)**, which gets the DPI of the screen and writes to an auxiliary variable.
That variable is used to decide if the position and size of the recording.

If that variable was not being updated, it will stay 96 which is 100%.
_(Thinking about it, I should rename that method to GetScreenScale, haha)_

Also, currently the app is not per-monitor DPI-aware. It uses a single DPI for all windows.

**Comment by NickeManarin** [comment] 2018-06-25 01:00
Btw, I asked about the version that you were using, because an old version had this problem.

**Comment by NickeManarin** [comment] 2019-09-27 22:32
I'm closing this issue as I cannot reproduce anymore.
Also, I changed the way that the app starts and detects the screen DPI.
Even so, if this bug still happens, you can try using the new recorder UI.
Head over to `Options > Application > Enable the new recorder UI`.

**Closed by NickeManarin** 2019-09-27 22:32 UTC
