### ISSUE TITLE
v2 Encoder Green Screen on Twitter

### ISSUE THREAD

**Issue by spottedmahn** [NickeManarin/ScreenToGif#327] opened 2018-05-25 14:30 UTC
**v2 Encoding**
![gaussin blur v2 encoder](https://user-images.githubusercontent.com/14079228/40549809-723cacc2-6006-11e8-89b5-073e8f6f388b.gif)

![image](https://user-images.githubusercontent.com/14079228/40549813-750578d0-6006-11e8-8774-8ec13531b995.png)

---

**v1 Encoding**
![gaussin blur](https://user-images.githubusercontent.com/14079228/40549851-8a34cc88-6006-11e8-9f60-e1ad1b223f4c.gif)

---

Is that a browser problem or an encoding problem?

**Comment by NickeManarin** [comment] 2018-05-26 00:48
Encoding. The V2 is guessing the wrong color when picking the color that will be treated as transparent. This happens when that color is present in a bunch of pixels on the source frame (It's probably the color whell at the bottom left corner).   

Here's where you can change that color to something like magenta:

![Where to change](https://user-images.githubusercontent.com/14798947/40570828-4cf68302-6065-11e8-8c0f-3bca40602eb2.png)

**Comment by spottedmahn** [comment] 2018-05-26 01:06
I will try that and report back, thanks 🙏!

**Comment by spottedmahn** [comment] 2018-05-26 20:47
Still no luck...

![gaussin blur v2 encoder - magenta test](https://user-images.githubusercontent.com/14079228/40580045-563b6dac-6104-11e8-903e-792bc039bc42.gif)

![image](https://user-images.githubusercontent.com/14079228/40580047-607b9b52-6104-11e8-8e8f-61fbadf52e36.png)

**Comment by NickeManarin** [comment] 2018-05-26 20:57
Oh. :/ 
Can you share the project with me?

**Comment by spottedmahn** [comment] 2018-05-26 21:01
Sure 😊

[Gaussin Blur v2 Encoder - magenta test.stg](https://1drv.ms/u/s!AmsBn7YVdmXPhfUkXBqQnJBrmHZN8Q)

**Comment by NickeManarin** [comment] 2018-05-27 22:19
I was analyzing the recording. There's something strange happening.
Frame # 349 has a different dpi than frame 350.

I think that it's caused by the "Show mouse clicks" option that was turned on. I'll fix this issue.

Anyway, I was going to propose to hide the color wheel with some other color, like black or white. But then I found out the other bug above.

**Comment by spottedmahn** [comment] 2018-05-28 14:33
>I think that it's caused by the "Show mouse clicks" option that was turned on

Didn't know about that!  Sounds like a cool 😎 feature!

Thanks for debugging it! 🥇

**Comment by spottedmahn** [comment] 2018-05-28 14:46
BTW, the DPI change must have something to do w/ my setup.

I have 3 monitors.  2 are ~22" 1080p.  The other one is my 15" laptop monitor.

I was probably trying to record the full screen.  Maybe from monitor 3:

![image](https://user-images.githubusercontent.com/14079228/40619735-3b5954de-6264-11e8-9cc3-81ebca5eb11a.png)

The stop icon in ScreenToGif was probably in monitor 1.

**Comment by spottedmahn** [comment] 2018-08-16 14:55
Hi @NickeManarin - FYI, I'm still seeing this problem w/ v2 encoder 😢

How can I help get this fixed?  Thanks!

**Comment by ParticleCore** [comment] 2019-11-15 15:56
To get around this problem use a dummy color that is not present in the original video, otherwise the engine will get confused and mix the dummy color and the same color from the video which leads to the corrupted result.

If you cannot by any means use any color, for example the original post contains a color wheel, disable the use of the dummy color all together, but this will result in a file with a bigger size.

**Comment by NickeManarin** [comment] 2019-11-15 17:18
@spottedmahn Oh, I totally forgot about this issue. I'm sorry, I can't keep up.

As explained by @ParticleCore, it's the same idea as before, try hiding any color that is marked as the chroma key.

**Closed by NickeManarin** 2019-11-15 17:18 UTC

**Comment by spottedmahn** [comment] 2019-11-18 16:36
>If you cannot by any means use any color, for example the original post contains a color wheel, disable the use of the dummy color altogether, but this will result in a file with a bigger size.

I see, thanks @ParticleCore 👍

**for reference:**
![image](https://user-images.githubusercontent.com/14079228/69068002-09d65b00-09f2-11ea-8731-c70b0a6d1f20.png)
